#!/usr/bin/env node
import { cac } from "cac";
import { join, resolve as resolvePath, basename } from "node:path";
import { existsSync, mkdirSync, readdirSync, writeFileSync, readFileSync } from "node:fs";
import { parse as parseYaml } from "yaml";
import type { IR } from "./types.js";
import { irSchema } from "./schemas.js";

const cli = cac("aivion-qa");

// ── init ──────────────────────────────────────────────────────────────────────
cli.command("init", "Scaffold qa.config.yaml, .aivion-qa/ (plans + cache), reports/").action(async () => {
  const cwd = process.cwd();

  if (
    existsSync(join(cwd, ".aivion-qa", "qa.config.yaml")) ||
    existsSync(join(cwd, "qa.config.yaml"))
  ) {
    console.error("qa.config.yaml already exists. Aborting.");
    process.exit(1);
  }

  mkdirSync(join(cwd, ".aivion-qa", "plans"), { recursive: true });
  mkdirSync(join(cwd, ".aivion-qa", "reports"), { recursive: true });

  writeFileSync(join(cwd, ".aivion-qa", "qa.config.yaml"), CONFIG_TEMPLATE);
  writeFileSync(join(cwd, ".env.example"), ENV_TEMPLATE);
  writeFileSync(join(cwd, ".aivion-qa", "plans", "example.yaml"), PLAN_TEMPLATE);

  // Gitignore strategy:
  //   .aivion-qa/*.yaml and base.yaml → TRACKED (authored plans, commit these)
  //   .aivion-qa/schema.json          → IGNORED (regenerated by `qa learn`)
  //   reports/                      → IGNORED (per-run artifacts)
  //   .env                          → IGNORED (secrets)
  const gitignorePath = join(cwd, ".gitignore");
  const gitignoreSnippet = [
    "",
    "# qa-tools",
    ".aivion-qa/schema.json",
    ".aivion-qa/profile.json",
    ".aivion-qa/compiled/",
    ".aivion-qa/reports/",
    ".env",
    "",
  ].join("\n");
  if (existsSync(gitignorePath)) {
    const existing = readFileSync(gitignorePath, "utf8");
    if (!existing.includes(".aivion-qa/schema.json")) {
      writeFileSync(gitignorePath, existing + gitignoreSnippet);
    }
  } else {
    writeFileSync(gitignorePath, gitignoreSnippet.trimStart());
  }

  console.log("Initialized qa-tools project:");
  console.log("  .aivion-qa/qa.config.yaml      — base URLs, auth, DB config");
  console.log("  .aivion-qa/plans/              — put your plan YAMLs here");
  console.log("  .aivion-qa/plans/example.yaml  — starter plan (edit or replace)");
  console.log("  .aivion-qa/reports/            — per-run reports land here (git-ignored)");
  console.log("  .env.example                 — copy to .env and fill in secrets");
  console.log("\nNext: `qa doctor` to verify your stack is reachable.");
});

// ── doctor ───────────────────────────────────────────────────────────────────
cli.command("doctor", "Verify connectivity: URL, DB, Clerk").action(async () => {
  const { loadConfig, getProjectRoot } = await import("./config.js");
  const config = loadConfig();
  const root = getProjectRoot();
  let ok = true;

  console.log("aivion-qa doctor\n");

  // Check URLs
  for (const [name, url] of Object.entries(config.baseUrls)) {
    try {
      const res = await fetch(url, { signal: AbortSignal.timeout(5000) });
      console.log(`  [✓] ${name}: ${url} (${res.status})`);
    } catch (err) {
      console.log(`  [✗] ${name}: ${url} — ${(err as Error).message}`);
      ok = false;
    }
  }

  // Check DB
  try {
    const { Pool } = await import("pg");
    const dbUrl = process.env[config.db.connectionStringEnv];
    if (!dbUrl) throw new Error(`${config.db.connectionStringEnv} not set`);

    // `pg` silently strips non-standard URL dialects like `postgresql+asyncpg://`.
    // Warn so users don't ship a SQLAlchemy-style URL that only works by accident.
    const scheme = dbUrl.split("://")[0] ?? "";
    if (scheme !== "postgresql" && scheme !== "postgres") {
      console.log(`  [!] database: URL scheme "${scheme}://" is non-standard for Node pg — expected "postgresql://". pg will tolerate it, but consider normalizing.`);
    }

    const pool = new Pool({ connectionString: dbUrl });
    await pool.query("SELECT 1");
    await pool.end();
    console.log(`  [✓] database: connected (SELECT 1)`);
  } catch (err) {
    console.log(`  [✗] database: ${(err as Error).message}`);
    ok = false;
  }

  // Check Clerk
  try {
    const key = process.env[config.auth.secretKeyEnv];
    if (!key) throw new Error(`${config.auth.secretKeyEnv} not set`);
    const res = await fetch("https://api.clerk.com/v1/users?limit=1", {
      headers: { Authorization: `Bearer ${key}` },
    });
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    console.log(`  [✓] clerk: API key valid`);
  } catch (err) {
    console.log(`  [✗] clerk: ${(err as Error).message}`);
    ok = false;
  }

  // Check Playwright browsers
  try {
    const { chromium } = await import("playwright");
    const execPath = chromium.executablePath();
    if (!existsSync(execPath)) {
      console.log(`  [✗] playwright chromium: not installed`);
      console.log(`       Fix: aivion-qa install-browsers  (or: npx playwright install chromium)`);
      ok = false;
    } else {
      console.log(`  [✓] playwright chromium: installed`);
    }
  } catch (err) {
    console.log(`  [✗] playwright chromium: ${(err as Error).message}`);
    ok = false;
  }

  // Check AI
  if (config.ai.mode === "claude_cli") {
    const { execFile } = await import("node:child_process");
    const { promisify } = await import("node:util");
    const execFileAsync = promisify(execFile);
    try {
      await execFileAsync("claude", ["--version"], { timeout: 5000 });
      console.log(`  [✓] claude CLI: found`);
    } catch {
      console.log(`  [!] claude CLI: not found — install Claude Code or switch to sdk mode`);
    }
  }

  console.log(ok ? "\nAll checks passed." : "\nSome checks failed. Fix the issues above before running plans.");
  process.exit(ok ? 0 : 1);
});

// ── install-browsers ─────────────────────────────────────────────────────────
cli.command("install-browsers", "Download Playwright's Chromium (~300MB, one-time)")
  .action(async () => {
    const { spawnSync } = await import("node:child_process");
    console.log("Running: npx playwright install chromium");
    const result = spawnSync("npx", ["playwright", "install", "chromium"], {
      stdio: "inherit",
      shell: false,
    });
    if (result.status !== 0) {
      console.error(`\nBrowser install failed (exit ${result.status}). ` +
        `You can also run directly: npx playwright install chromium`);
      process.exit(result.status ?? 1);
    }
    console.log("\nChromium installed. Run `aivion-qa doctor` to verify.");
  });

// ── learn ────────────────────────────────────────────────────────────────────
cli.command("learn", "Phase 0: analyze DB schema → .aivion-qa/schema.json").action(async () => {
  const { loadConfig, getProjectRoot } = await import("./config.js");
  const { learnSchema } = await import("./learn.js");

  const config = loadConfig();
  const root = getProjectRoot();
  const qaToolDir = resolveQaToolDir(root);

  const analysis = await learnSchema(config, qaToolDir);
  console.log(`\nAnalyzed ${analysis.tables.length} tables. Schema hash: ${analysis.schemaHash}`);
});

// ── validate ─────────────────────────────────────────────────────────────────
cli.command("validate <plan>", "Zod-check a plans/<plan>.yaml without running")
  .action(async (plan: string) => {
    const { getProjectRoot } = await import("./config.js");
    const root = getProjectRoot();
    const planPath = resolvePlanPath(plan, root);
    const ir = loadIrFromDisk(planPath);
    console.log(`[✓] ${planPath} — ${(ir.cases ?? []).length} cases, schema OK`);
  });

// ── run ──────────────────────────────────────────────────────────────────────
cli.command("run [plan]", "Execute a YAML plan")
  .option("--all", "Run all YAML plans in plans/")
  .option("--fail-fast", "Stop after first failure")
  .option("--headed", "Run browser in headed (non-headless) mode")
  .action(async (plan: string | undefined, opts: { all?: boolean; failFast?: boolean; headed?: boolean }) => {
    const { loadConfig, getProjectRoot } = await import("./config.js");
    const { executeIr } = await import("./runner/executor.js");
    const { writeReport, printReportSummary } = await import("./reporter.js");

    const config = loadConfig();
    const root = getProjectRoot();
    const qaToolDir = resolveQaToolDir(root);
    const reportsDir = resolveReportsDir(root);
    mkdirSync(reportsDir, { recursive: true });

    let plans: string[] = [];

    if (opts.all) {
      const plansDir = resolvePlansDir(root);
      plans = readdirSync(plansDir)
        .filter(f => /\.(yaml|yml)$/.test(f) && f !== "base.yaml" && f !== "base.yml")
        .map(f => join(plansDir, f));
    } else if (plan) {
      plans = [resolvePlanPath(plan, root)];
    } else {
      console.error("Specify a plan name or --all");
      process.exit(1);
    }

    let anyFail = false;

    for (const planPath of plans) {
      const planName = planNameFromPath(planPath);
      console.log(`\n${"═".repeat(50)}`);
      console.log(`Running: ${planName}`);
      console.log("═".repeat(50));

      const ir = loadIrFromDisk(planPath);

      const { report, reportDir } = await executeIr({
        ir,
        config,
        reportsDir,
        qaToolDir,
        planName,
        failFast: opts.failFast ?? false,
        headless: !opts.headed,
      });

      const reportPath = await writeReport(report, ir, reportDir, config);
      printReportSummary(report);
      console.log(`Report: ${reportPath}`);

      if (report.failed > 0) anyFail = true;
    }

    process.exit(anyFail ? 1 : 0);
  });

// ── report ────────────────────────────────────────────────────────────────────
cli.command("report [path]", "Open the latest report (or a specific one)").action(async (reportPath?: string) => {
  const { getProjectRoot } = await import("./config.js");
  const { execFile } = await import("node:child_process");

  const root = getProjectRoot();
  const reportsDir = resolveReportsDir(root);

  let target: string;
  if (reportPath) {
    target = resolvePath(reportPath);
  } else {
    const dirs = readdirSync(reportsDir).sort();
    if (dirs.length === 0) {
      console.error("No reports found. Run `qa run <plan>` first.");
      process.exit(1);
    }
    target = join(reportsDir, dirs.at(-1)!, "report.md");
  }

  if (!existsSync(target)) {
    console.error(`Report not found: ${target}`);
    process.exit(1);
  }

  console.log(readFileSync(target, "utf8"));
});

// ── helpers ───────────────────────────────────────────────────────────────────

/** Candidate directories for authored plans, in priority order. */
const PLANS_DIR_CANDIDATES = [
  ".aivion-qa/plans",   // preferred (current default)
  ".aivion-qa",         // flat layout (early migration)
  ".qa-tool/plans",     // legacy (pre-rename)
  ".qa-tool",           // legacy flat
  "plans",              // oldest legacy
] as const;

/**
 * Resolve a plan name to an absolute `.yaml`/`.yml` path. Searches the
 * candidate directories in priority order.
 */
function resolvePlanPath(plan: string, root: string): string {
  if (existsSync(plan) && /\.(yaml|yml)$/.test(plan)) return resolvePath(plan);
  const base = plan.replace(/\.(yaml|yml)$/, "");
  for (const dir of PLANS_DIR_CANDIDATES) {
    for (const ext of ["yaml", "yml"] as const) {
      const p = join(root, dir, `${base}.${ext}`);
      if (existsSync(p)) return p;
    }
  }
  throw new Error(`Plan not found: ${plan}. Searched: ${PLANS_DIR_CANDIDATES.join(", ")}`);
}

/** Base tool dir for cache (schema.json, compiled IR, etc.). */
function resolveQaToolDir(root: string): string {
  for (const dir of [".aivion-qa", ".qa-tool"]) {
    const abs = join(root, dir);
    if (existsSync(abs)) return abs;
  }
  return join(root, ".aivion-qa");
}

/** Reports dir — prefer .aivion-qa/reports/, fall back to legacy locations. */
function resolveReportsDir(root: string): string {
  const candidates = [
    join(root, ".aivion-qa", "reports"),
    join(root, ".qa-tool", "reports"),
    join(root, "reports"),
  ];
  for (const c of candidates) if (existsSync(c)) return c;
  return candidates[0]; // new default — will be created
}

/** Which plans dir is actually in use for this project. */
function resolvePlansDir(root: string): string {
  for (const dir of PLANS_DIR_CANDIDATES) {
    const abs = join(root, dir);
    if (existsSync(abs) && readdirSync(abs).some(f => /\.(yaml|yml)$/.test(f) && f !== "qa.config.yaml")) {
      return abs;
    }
  }
  return join(root, PLANS_DIR_CANDIDATES[0]);
}

function planNameFromPath(path: string): string {
  return basename(path).replace(/\.(yaml|yml)$/, "");
}

/** Load a YAML or JSON IR file from disk, merge with plans/base.yaml if present,
 *  flatten URL groups into cases, and validate against the Zod schema. */
function loadIrFromDisk(path: string): IR {
  const raw = readFileSync(path, "utf8");
  const data = path.endsWith(".json") ? JSON.parse(raw) : parseYaml(raw);

  // Merge with base.yaml if present in the same plans/ directory
  const plansDir = path.replace(/\/[^/]+$/, "");
  for (const baseName of ["base.yaml", "base.yml"]) {
    const basePath = `${plansDir}/${baseName}`;
    if (existsSync(basePath) && basePath !== path) {
      const baseData = parseYaml(readFileSync(basePath, "utf8"));
      mergeBase(data, baseData);
      break;
    }
  }

  // Flatten URL groups into cases. Each group prepends a browser.goto to
  // every case's actions so the executor doesn't need group awareness.
  if (data && typeof data === "object" && Array.isArray((data as Record<string, unknown>).groups)) {
    const groups = (data as { groups: Array<{ url: string; cases: Array<Record<string, unknown>> }> }).groups;
    const flatCases: Array<Record<string, unknown>> = [];
    for (const group of groups) {
      for (const c of group.cases) {
        const existingActions = Array.isArray(c.actions) ? (c.actions as Array<unknown>) : [];
        flatCases.push({
          ...c,
          actions: [{ "browser.goto": group.url }, ...existingActions],
        });
      }
    }
    (data as Record<string, unknown>).cases = [
      ...((data as { cases?: Array<unknown> }).cases ?? []),
      ...flatCases,
    ];
    delete (data as Record<string, unknown>).groups;
  }

  const result = irSchema.safeParse(data);
  if (!result.success) {
    const issues = result.error.issues
      .map(i => `  - ${i.path.join(".") || "<root>"}: ${i.message}`)
      .join("\n");
    throw new Error(`${path} failed schema validation:\n${issues}`);
  }
  return result.data as IR;
}

/** Merge base.yaml values into the plan. Plan's values always win on conflict;
 *  base fills gaps. Arrays (like teardown.sql) are concatenated: base first,
 *  then plan. */
function mergeBase(plan: unknown, base: unknown): void {
  if (!plan || !base || typeof plan !== "object" || typeof base !== "object") return;
  const p = plan as Record<string, unknown>;
  const b = base as Record<string, unknown>;

  for (const key of Object.keys(b)) {
    const bv = b[key];
    const pv = p[key];
    if (pv === undefined) {
      p[key] = bv;
    } else if (Array.isArray(pv) && Array.isArray(bv)) {
      p[key] = [...bv, ...pv];
    } else if (typeof pv === "object" && typeof bv === "object" && !Array.isArray(pv)) {
      mergeBase(pv, bv);
    }
    // Otherwise plan value wins (scalar conflict).
  }
}

// ── templates ─────────────────────────────────────────────────────────────────
const CONFIG_TEMPLATE = `# qa-tools configuration
# Commit this file. Keep secrets in .env (git-ignored).

baseUrls:
  app: http://localhost:3000
  # api: http://localhost:8000   # uncomment if you have a separate API server

auth:
  provider: clerk
  secretKeyEnv: CLERK_SECRET_KEY   # env var name (not the value)

db:
  connectionStringEnv: DATABASE_URL  # env var name (not the value)
  userTable: users                   # anchor table for auto cleanup + schema-aware asserts
  userEmailColumn: email             # email lookup column on userTable
  # cleanupExcludeTables:             # optional — tables to skip during FK-walk cleanup
  #   - audit_logs
  #   - billing_events

ai:
  mode: off              # DEFAULT — zero LLM. Plans must use typed asserts only.
                         # Set to claude_cli or sdk to enable ai_check + end-of-run summary.

  # mode: claude_cli     # uses your local Claude Code install + subscription
  # model: sonnet        # "opus" | "sonnet" | "haiku" | full id

  # mode: sdk            # API-key based (CI, non-Claude providers)
  # sdk:
  #   provider: anthropic
  #   model: claude-sonnet-4-6
  #   apiKeyEnv: ANTHROPIC_API_KEY

  # tasks:               # per-task model override (works in claude_cli and sdk)
  #   ai_check: { model: sonnet }
  #   summary:  { model: haiku }
`;

const ENV_TEMPLATE = `# Copy this to .env and fill in real values. Never commit .env.
CLERK_SECRET_KEY=sk_test_...
DATABASE_URL=postgresql://user:password@localhost:5432/mydb
# ANTHROPIC_API_KEY=sk-ant-...   # only needed if ai.mode = sdk with anthropic provider
`;

const PLAN_TEMPLATE = `# Example QA plan — hand-authored YAML.
# Full schema reference: see doc/PLAN_GUIDELINES.md.

meta:
  plan: example
  testUser:
    email: "example+clerk_test+{run_id}@gmail.com"   # {run_id} is substituted at execute time
    password: "QaTool-{run_id}-Run!"                  # {run_id} keeps it unique vs HIBP
  environments:
    app: http://localhost:3000

# setup is optional. Include setup.auth.createUser only if the test assumes a
# pre-existing user (login flows). Omit for signup flows — the test creates it.
# setup:
#   auth:
#     createUser: { email: "{{meta.test_user.email}}", via: clerk }

cases:
  - id: "1.1"
    title: Login page loads
    actions:
      - browser.goto: /login
    asserts:
      - type: expect_text
        text: Sign in

  - id: "1.2"
    title: Successful sign-in
    actions:
      - browser.goto: /login
      - browser.fill_form: { from: test_user }
      - browser.submit: true
    asserts:
      - type: expect_url
        pattern: /
      - type: db_eventually
        sql: "SELECT id FROM users WHERE email = $1"
        params: ["{{meta.test_user.email}}"]
        expect: non_empty
        timeoutMs: 10000

teardown:
  sql:
    - sql: "DELETE FROM users WHERE email = $1"
      params: ["{{meta.test_user.email}}"]
  auth:
    cleanupUser: "{{meta.test_user.email}}"
`;

cli.help();
cli.version("0.1.0");
cli.parse();
